-- Dune Dragon — Seed (refleja el contenido actual). Correr DESPUÉS de schema.sql.

-- ── Textos editables ──
insert into site_content (id, value) values
  ('beneficios_subtitle', 'Dune Dragon'),
  ('beneficios_title', '¿Por qué elegirnos?'),
  ('contacto_eyebrow', 'Estamos para ayudarte'),
  ('contacto_title', 'Contacto'),
  ('contacto_cta_title', '¿Listo para hacer tu pedido?'),
  ('contacto_cta_text', 'Escríbenos directo por WhatsApp y te respondemos al instante.'),
  ('contacto_whatsapp', '+56 9 4234 8587'),
  ('contacto_zona', 'Todo Chile'),
  ('contacto_horario', 'Lun – Sáb, 9:00 – 20:00')
on conflict (id) do nothing;

-- ── Temporada Default + sus 5 destacados ──
insert into campaigns (name, is_active, is_default, sort_order)
select 'Default', true, true, 0
where not exists (select 1 from campaigns where is_default);

insert into featured_items (campaign_id, position, name, price, product_image_url, color, feature_key, img_w, img_x, img_y, arrow_w, arrow_x, arrow_y, arrow_r)
select c.id, v.position, v.name, v.price, v.product_image_url, v.color, v.feature_key, v.img_w, v.img_x, v.img_y, v.arrow_w, v.arrow_x, v.arrow_y, v.arrow_r
from campaigns c cross join (values
  (0, 'AirPods Pro 2', '$ 26.000', './images/prod-pro2.webp', 'rosa', 'airpods-pro-2', '95%', 0, -19, 55, 0, -250, 0),
  (1, 'AirPods 4', '$ 30.000', './images/prod-4.webp', 'amarillo', 'airpods-4gen', '98%', 0, -19, 55, 0, -250, 0),
  (2, 'AirPods Max', '$ 47.000', './images/prod-max.webp', 'celeste', 'max-basico', '90%', 25, -38, 55, 0, -250, 0),
  (3, 'MagSafe', '$ 22.000', './images/prod-magsafe.webp', 'rosa', 'bateria-magsafe', '220%', 0, -10, 55, 0, -250, 0),
  (4, 'Cargador 35W', '$ 16.000', './images/cargador-tipo-c.webp', 'celeste', 'cargador-35w', '70%', 0, -15, 55, 0, -250, 0)
) as v(position, name, price, product_image_url, color, feature_key, img_w, img_x, img_y, arrow_w, arrow_x, arrow_y, arrow_r)
where c.is_default
on conflict (campaign_id, position) do nothing;

-- ── Catálogo ──
insert into catalog_products (feature_key, tag, name, price, raw_price, descr, image_url, img_scale, category, sort_order) values
  ('airpods-pro-2', 'Audio', 'AirPods Pro 2', '$26.000', 26000, 'Sonido profesional en un formato compacto. Pensados para quienes buscan una experiencia de audio superior y comodidad durante todo el día.', './images/airpods-pro-2.webp', 0.85, 'audio', 0),
  ('airpods-4gen', 'Audio', 'AirPods 4', '$30.000', 30000, 'Sonido espléndido en formato compacto. Modelo "Improved Fit" — si tus airpods lisos se resbalaban, estos vinieron a cambiarlo todo.', './images/airpods-4gen.webp', 0.85, 'audio', 1),
  ('airpods-pro-3', 'Audio · Nuevo', 'AirPods Pro 3 · ANC', '$37.990', 37990, 'Los audífonos pequeños con el sonido más espectacular. Acústica renovada, mejor ajuste y traductor en vivo.', './images/airpods-3gen.webp', 0.85, 'audio', 2),
  ('max-basico', 'Audio', 'AirPods Max Básico', '$47.000', 47000, 'Eleva tu forma de escuchar música. Diseñados para quienes buscan una experiencia de sonido inmersiva y comodidad superior.', './images/max-magneticos.webp', 0.85, 'audio', 3),
  ('max-1-1', 'Audio · Premium', 'AirPods Max 1:1', '$195.000', 195000, 'Disponible en 5 colores. Este modelo es realmente idéntico. Modo reposo en estuche, sensores dinámicos, acabados de lujo.', './images/max-magneticos.webp', 0.85, 'audio', 4),
  ('apple-watch-ultra-3', 'Watch · Nuevo', 'Apple Watch Ultra 3', '$54.990', 54990, 'Potencia, estilo y control desde tu muñeca. Combina un diseño imponente con funciones inteligentes.', './images/apple-watch-ultra-3.webp', 0.75, 'watch', 5),
  ('apple-watch-serie-11', 'Watch · Nuevo', 'Apple Watch Serie 11', '$54.990', 54990, 'Elegancia, estilo y control desde tu muñeca. Combina un diseño sutil con funciones inteligentes.', './images/serie-10.webp', 0.75, 'watch', 6),
  ('apple-pencil', 'Accesorios · Nuevo', 'Apple Pencil 1° Gen', '$29.990', 29990, 'Precisión profesional en cada trazo. Diseñado para escribir, dibujar y crear con máxima fluidez.', './images/pencil.webp', 0.75, 'accesorios', 7),
  ('cargador-35w', 'Accesorios · Nuevo', 'Cargador 35W USB-C', '$16.000', 16000, 'Carga al instante con este cargador rápido compatible con iPhone y cualquier dispositivo USB-C. 35W, 1mt de longitud.', './images/cargador-tipo-c.webp', 0.75, 'accesorios', 8),
  ('bateria-magsafe', 'Accesorios', 'Batería MagSafe', '$22.000', 22000, 'Olvídate de quedarte sin batería. La batería MagSafe inalámbrica es tu aliada perfecta para viajar o salir sin preocuparte.', './images/bateria-magsafe.webp', 0.75, 'accesorios', 9),
  ('correa-milanese', 'Watch · Nuevo', 'Correa Milanese', '$13.000', 13000, 'La pulsera Milanese Loop de malla de acero inoxidable confeccionada con máquinas italianas. Se adapta como un guante a tu muñeca y su cierre magnético se ajusta perfectamente a cualquier talla.', './images/milaneseplata.webp', 0.85, 'watch', 10),
  ('correa-sport', 'Watch · Nuevo', 'Correa Sport', '$10.000', 10000, 'Hecha de fluoroelastómero de alto rendimiento. Duradera, resistente y muy suave. Su material compacto y liso envuelve con elegancia tu muñeca.', './images/cosportstarlight.webp', 0.85, 'watch', 11),
  ('correa-trail', 'Watch · Nuevo', 'Correa Trail', '$10.000', 10000, 'Ultra delgada y liviana con tejido de nylon flexible de alta elasticidad. Incluye tira para ajuste rápido e hilos reflectantes en los bordes.', './images/coblack.webp', 0.85, 'watch', 12),
  ('correa-sport-2', 'Watch · Nuevo', 'Correa Sport 2', '$10.000', 10000, 'Liviana y elástica con fragmentos de colores combinados de forma aleatoria que le dan un toque único. Ideal para pista, montaña o gimnasio.', './images/cosport2blanca.webp', 0.85, 'watch', 13)
on conflict (feature_key) do nothing;

insert into catalog_features (feature_key, text, sort_order) values
  ('airpods-pro-2', 'Incluye cable tipo C', 0),
  ('airpods-pro-2', 'Reconocimiento inmediato', 1),
  ('airpods-pro-2', 'Duración batería 6-8 horas', 2),
  ('airpods-pro-2', 'Control táctil', 3),
  ('airpods-pro-2', 'Compatibles iOS & Android', 4),
  ('airpods-pro-2', 'Incluye 3 pares de almohadillas XS/S/L', 5),
  ('airpods-4gen', 'No incluye cable de carga', 0),
  ('airpods-4gen', 'Reconocimiento inmediato', 1),
  ('airpods-4gen', 'Duración batería 6-8 horas', 2),
  ('airpods-4gen', 'Control táctil', 3),
  ('airpods-4gen', 'Compatibles iOS & Android', 4),
  ('airpods-4gen', 'Excelentes graves', 5),
  ('airpods-pro-3', 'Cancelación de ruido activa', 0),
  ('airpods-pro-3', 'Traductor en vivo (iOS26+)', 1),
  ('airpods-pro-3', 'No incluye cable de carga', 2),
  ('airpods-pro-3', 'Reconocimiento inmediato', 3),
  ('airpods-pro-3', 'Duración batería 6-8 horas', 4),
  ('airpods-pro-3', 'Control táctil', 5),
  ('airpods-pro-3', 'Compatibles iOS & Android', 6),
  ('airpods-pro-3', 'Incluye 4 pares XXS/XS/S/L', 7),
  ('max-basico', 'Sin cancelación de ruido activa', 0),
  ('max-basico', 'Incluye cable carga USB-A', 1),
  ('max-basico', 'Incluye estuche Smartcase', 2),
  ('max-basico', 'Reconocimiento inmediato iOS', 3),
  ('max-basico', 'Duración batería 10-12 horas', 4),
  ('max-basico', 'Almohadillas imantadas', 5),
  ('max-basico', 'Almohadillas desmontables', 6),
  ('max-basico', 'Compatibles iOS & Android', 7),
  ('max-1-1', 'Cancelación de ruido activa', 0),
  ('max-1-1', 'Incluye cable carga USB-C', 1),
  ('max-1-1', 'Duración batería hasta 12 horas', 2),
  ('max-1-1', 'Compatible audio espacial iOS', 3),
  ('max-1-1', 'Compatible Siri', 4),
  ('max-1-1', 'Compatible iOS & Android', 5),
  ('max-1-1', 'Sonido alta fidelidad', 6),
  ('max-1-1', 'Incluye estuche 1:1', 7),
  ('max-1-1', 'Starlight · Midnight · Orange · Blue · Purple', 8),
  ('apple-watch-ultra-3', 'Cuerpo silver / correa negra', 0),
  ('apple-watch-ultra-3', 'Incluye cable carga USB-A', 1),
  ('apple-watch-ultra-3', 'Duración batería hasta 8 horas', 2),
  ('apple-watch-ultra-3', 'Vinculación App XRFIT', 3),
  ('apple-watch-ultra-3', 'Compatible iOS & Android', 4),
  ('apple-watch-ultra-3', 'Compatible Apple Health', 5),
  ('apple-watch-ultra-3', 'Llamadas, notificaciones, SMS', 6),
  ('apple-watch-ultra-3', 'Métricas: calorías / ritmo / distancia / O2', 7),
  ('apple-watch-serie-11', 'Cuerpo negro / correa negra', 0),
  ('apple-watch-serie-11', 'Incluye cable carga USB-A', 1),
  ('apple-watch-serie-11', 'Duración batería hasta 8 horas', 2),
  ('apple-watch-serie-11', 'Vinculación App XRFIT', 3),
  ('apple-watch-serie-11', 'Compatible iOS & Android', 4),
  ('apple-watch-serie-11', 'Compatible Apple Health', 5),
  ('apple-watch-serie-11', 'Llamadas, notificaciones, SMS', 6),
  ('apple-watch-serie-11', 'Métricas: calorías / ritmo / distancia / O2', 7),
  ('apple-pencil', 'Tecnología táctil', 0),
  ('apple-pencil', 'Carga Lightning en iPad', 1),
  ('apple-pencil', 'Respuesta rápida sin latencia', 2),
  ('apple-pencil', 'Duración batería 6-8 horas', 3),
  ('cargador-35w', 'Cable tipo cordón (no goma)', 0),
  ('cargador-35w', 'Carga USB-C', 1),
  ('cargador-35w', 'Carga rápida 35W', 2),
  ('cargador-35w', '1mt de largo', 3),
  ('cargador-35w', 'Compatible dispositivos USB-C', 4),
  ('bateria-magsafe', 'Carga inalámbrica imantada', 0),
  ('bateria-magsafe', 'Potencia 5.000mAh', 1),
  ('bateria-magsafe', 'Diseño delgado fácil de transportar', 2),
  ('bateria-magsafe', 'Compatible desde iPhone 12', 3),
  ('bateria-magsafe', 'Carga a través de Lightning', 4),
  ('bateria-magsafe', 'No incluye cable de carga', 5),
  ('correa-milanese', 'Malla de acero inoxidable', 0),
  ('correa-milanese', 'Cierre magnético ajustable', 1),
  ('correa-milanese', 'Acabado italiano', 2),
  ('correa-milanese', 'Compatible Apple Watch', 3),
  ('correa-milanese', 'Talla universal', 4),
  ('correa-sport', 'Fluoroelastómero de alto rendimiento', 0),
  ('correa-sport', 'Duradera y resistente', 1),
  ('correa-sport', 'Cierre de encastre innovador', 2),
  ('correa-sport', 'Compatible Apple Watch', 3),
  ('correa-trail', 'Nylon flexible de alta elasticidad', 0),
  ('correa-trail', 'Tira de ajuste rápido', 1),
  ('correa-trail', 'Hilos reflectantes', 2),
  ('correa-trail', 'Ultra delgada y liviana', 3),
  ('correa-trail', 'Compatible Apple Watch', 4),
  ('correa-sport-2', 'Elástica y liviana', 0),
  ('correa-sport-2', 'Diseño perforado', 1),
  ('correa-sport-2', 'Fragmentos de colores aleatorios', 2),
  ('correa-sport-2', 'Compatible Apple Watch', 3)
on conflict (feature_key, text) do nothing;

insert into catalog_images (feature_key, image_url, sort_order) values
  ('airpods-pro-2', './images/airpods-pro-2.webp', 0),
  ('airpods-pro-2', './images/airpods-pro-2-v2.webp', 1),
  ('airpods-pro-2', './images/airpods-pro-2-v3.webp', 2),
  ('airpods-4gen', './images/airpods-4gen.webp', 0),
  ('airpods-4gen', './images/airpods-4ta-generacion-v2.webp', 1),
  ('airpods-4gen', './images/airpods-4ta-generacion-v3.webp', 2),
  ('airpods-pro-3', './images/airpods-3gen.webp', 0),
  ('airpods-pro-3', './images/airpods-3ra-generacion-v2.webp', 1),
  ('airpods-pro-3', './images/airpods-3ra-generacion-v3.webp', 2),
  ('max-basico', './images/max-magneticos.webp', 0),
  ('max-1-1', './images/max-negros.webp', 0),
  ('max-1-1', './images/max-blanco.webp', 1),
  ('max-1-1', './images/max-naranja.webp', 2),
  ('max-1-1', './images/max-morado.webp', 3),
  ('max-1-1', './images/max-azul.webp', 4),
  ('apple-watch-ultra-3', './images/apple-watch-ultra-3.webp', 0),
  ('apple-watch-ultra-3', './images/apple-watch-ultra-3-v2.webp', 1),
  ('apple-watch-ultra-3', './images/apple-watch-ultra-3-v3.webp', 2),
  ('apple-watch-serie-11', './images/serie-10.webp', 0),
  ('apple-watch-serie-11', './images/apple-watch-serie-10-v2.webp', 1),
  ('apple-watch-serie-11', './images/apple-watch-serie-10-v3.webp', 2),
  ('apple-pencil', './images/pencil.webp', 0),
  ('apple-pencil', './images/pencilv2.webp', 1),
  ('cargador-35w', './images/cargador-tipo-c.webp', 0),
  ('cargador-35w', './images/cargador-tipo-c-completo-v2.webp', 1),
  ('bateria-magsafe', './images/bateria-magsafe.webp', 0),
  ('bateria-magsafe', './images/bateria-magsafe-v2.webp', 1)
on conflict (feature_key, image_url) do nothing;

insert into catalog_color_variants (feature_key, name, hex, img_url, swatch_url, thumb_url, sort_order) values
  ('max-1-1', 'Midnight', '#1A1A1A', './images/max-negros.webp', './images/black.png', './images/miblack.webp', 0),
  ('max-1-1', 'Starlight', '#F5F0E8', './images/max-blanco.webp', './images/starlight.png', './images/miblanco.webp', 1),
  ('max-1-1', 'Orange', '#F26513', './images/max-naranja.webp', './images/orange.png', './images/miorange.webp', 2),
  ('max-1-1', 'Purple', '#9B59B6', './images/max-morado.webp', './images/purple.webp', './images/mipurple.webp', 3),
  ('max-1-1', 'Blue', '#3498DB', './images/max-azul.webp', './images/blue.png', './images/miblue.webp', 4),
  ('correa-milanese', 'Plata', '#C0C0C0', './images/milaneseplata.webp', './images/mplata.webp', './images/mplata.webp', 0),
  ('correa-milanese', 'Vintage', '#C9A96E', './images/milanesevintage.webp', './images/mvintage.webp', './images/mvintage.webp', 1),
  ('correa-milanese', 'Black', '#1A1A1A', './images/milaneseblack.webp', './images/mblack.webp', './images/mblack.webp', 2),
  ('correa-sport', 'Starlight', '#F5F0E8', './images/cosportstarlight.webp', './images/mstarlight.webp', './images/mstarlight.webp', 0),
  ('correa-sport', 'Black', '#1A1A1A', './images/cosportblack.webp', './images/mblack.webp', './images/mblack.webp', 1),
  ('correa-sport', 'Menta', '#98D8C8', './images/cosportmenta.webp', './images/mmenta.webp', './images/mmenta.webp', 2),
  ('correa-sport', 'Olivia', '#6B8E23', './images/cosportolivia.webp', './images/molivia.webp', './images/molivia.webp', 3),
  ('correa-sport', 'Rosa', '#F4A7B9', './images/cosportrosa.webp', './images/mrosa.webp', './images/mrosa.webp', 4),
  ('correa-trail', 'Black', '#1A1A1A', './images/coblack.webp', './images/mblack.webp', './images/mblack.webp', 0),
  ('correa-trail', 'Beige-Rosa', '#D4A99A', './images/cobeigerosa.webp', './images/mbeigerosa.webp', './images/mbeigerosa.webp', 1),
  ('correa-trail', 'Roja', '#C41E3A', './images/coroja.webp', './images/mroja.webp', './images/mroja.webp', 2),
  ('correa-trail', 'Sunshine', '#F5C542', './images/cosunhine.webp', './images/msunshine.webp', './images/msunshine.webp', 3),
  ('correa-trail', 'Gris', '#9E9E9E', './images/cogris.webp', './images/mgris.webp', './images/mgris.webp', 4),
  ('correa-sport-2', 'Blanca', '#FAFAFA', './images/cosport2blanca.webp', './images/mblanca.webp', './images/mblanca.webp', 0),
  ('correa-sport-2', 'Negra', '#1A1A1A', './images/cosport3black.webp', './images/mblack.webp', './images/mblack.webp', 1),
  ('correa-sport-2', 'N-Verde', '#4CAF50', './images/cosport2nverde.webp', './images/mverde.webp', './images/mverde.webp', 2),
  ('correa-sport-2', 'Rosa', '#F4A7B9', './images/cosport2rosa.webp', './images/mrosa.webp', './images/mrosa.webp', 3),
  ('correa-sport-2', 'Caqui', '#8B7355', './images/cosport2caqui.webp', './images/mcaqui.webp', './images/mcaqui.webp', 4)
on conflict (feature_key, name) do nothing;
